replicaCount: 1

image:
  repository: 10.10.10.100:8081/devops-docker/product-service
  tag: "0.0.1-15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

config:
  datasourceUrl: jdbc:postgresql://postgres:5432/product_db
  hibernateDdlAuto: update

postgresSecret:
  name: postgres-credentials
  usernameKey: username
  passwordKey: password

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi