spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: update

product-service:
  base-url: http://localhost:8080

server:
  port: 8081