apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_db
  SPRING_JPA_HIBERNATE_DDL_AUTO: update