apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: devops
spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
        - name: order-service
          image: 10.10.10.100:8081/devops-docker/order-service:0.0.1-15
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8081

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO

            - name: PRODUCT_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: PRODUCT_SERVICE_BASE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi